.POSIX:
CC      = cc
CFLAGS  = -Os -Wall -Wextra -D__USE_MINGW_ANSI_STDIO=0
LDFLAGS = -s -Wl,--no-insert-timestamp
LDLIBS  =

xxtea.exe: xxtea.c
	$(CC) $(CFLAGS) $(LDFLAGS) -o $@ xxtea.c $(LDLIBS)

clean:
	rm -f xxtea.exe
